name = "Sub2Index"
uuid = "18bf2a15-c698-460b-8f18-fd6197740d83"
authors = ["GOTOH Shunsuke <antimon2.me@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
